### ISSUE TITLE
Missing dataset folder img_test

### ISSUE THREAD

**Issue by nickls** [sibozhang/vid2vid#4]
Fixed it :)

**Comment by nickls** [comment]
@sibozhang  -- Hi Michael, I enjoyed reading your paper but have had some trouble getting the sample code to work.

Thanks in advance.

**Comment by chinaczm** [comment]
> 

Hello , how did you solved this problem?

**Comment by nickls** [comment]
Hi @chinaczm 

The img_test folder is generated by a previous step in the colab notebook. I incorrectly thought it was supposed to be included in this `vid2vid` repository.

The step below was failing and it was printing an error but not returning an error exit code so the cells below got executed. I missed the error but once you fix that (I think it was a missing package) the `img_test` folder is then created and filled.

```
%cd /content/FACIAL/audio2face
! python fintuning2-trainheadpose.py 
```

Good luck and let me know if you still need help.

**Comment by KaiyuHu2001** [comment]
> Hi @chinaczm
> 
> The img_test folder is generated by a previous step in the colab notebook. I incorrectly thought it was supposed to be included in this `vid2vid` repository.
> 
> The step below was failing and it was printing an error but not returning an error exit code so the cells below got executed. I missed the error but once you fix that (I think it was a missing package) the `img_test` folder is then created and filled.
> 
> ```
> %cd /content/FACIAL/audio2face
> ! python fintuning2-trainheadpose.py 
> ```
> 
> Good luck and let me know if you still need help.

hi, sorry to bother, where is the colab notebook? i can't find it in this repo.
